### ISSUE TITLE
mewatchsg.samsam123.name.my got redirected to chinatelecomantifraud.pages.dev

### ISSUE THREAD

**Issue by win98se** [samleong123/samleong123#1]
I know https://github.com/samleong123/mewatchsg is now archived, but the domain name seems to got hacked by PRC government (whether itself or its fans).

**Comment by samleong123** [comment]
Hi, this was intentional. For my subdomain that does not have an A, AAAA, or CNAME record will be redirected to the anti-fraud page to prevent malicious resolution.
